DELIMITER //
CREATE TRIGGER AGGIORNA_DISPONIBILITA3
AFTER INSERT ON ACQUISTO
FOR EACH ROW
BEGIN

UPDATE VERSIONE_COMPONENTE
SET Quantita_venduta = Quantita_venduta + 1
WHERE Id_Versione = NEW.Componente;

END //